Gblagov
Axway/docker-st pull request #1
Opened 2020-05-08 15:42 UTC by georgi-blagov

Update Dockerfile, README and configurations

2020-05-11 07:01 UTC, pavel-vasilev-georgiev-axway commented on backend/Dockerfile
> +LABEL org.opencontainers.image.source="git@git.ecd.axway.int:cloud/docker-st.git"
git@github.com:Axway/docker-st.git

2020-05-11 10:27 UTC, pavel-vasilev-georgiev-axway requested changes

2020-05-11 11:44 UTC, pavel-vasilev-georgiev-axway commented on backend/example-configuration/HaProxy/haproxy.cfg
> +    accepted_payload_size 8192
Let;s use "parse-resolv-conf" instead of "nameserver dns1 10.96.0.10:53:

2020-05-11 12:03 UTC, pavel-vasilev-georgiev-axway commented on edge/Dockerfile
> +LABEL org.opencontainers.image.documentation="https://docs.axway.com/category/mft"
1) use the github rep for the links (see my previous comment for the backend)
2) Remove the last _**org.opencontainers.image.documentation="https://docs.axway.com/category/mft"**_ as it's duplicate

2020-05-11 12:10 UTC, pavel-vasilev-georgiev-axway commented on edge/example-configuration/HaProxy/client/haproxy.cfg
> +    accepted_payload_size 8192
Same comment as the Backend:
resolvers kube-dns
    parse-resolv-conf
    accepted_payload_size 8192
    hold valid            4s

2020-05-12 13:37 UTC, pavel-vasilev-georgiev-axway commented on README.md
The github repo should contain full blown yml files to serve as working examples - the details are in the Deployment Guide. For example - the guide says tha tthe Edge requires external mysql db. That's it. In the Github repo we can put a k8s yml file to deploy mysql single node db for playing with the solution.
Ful haproxy.cfg files should also be part of the github repo - only the most important required parts related to haproxy must be docuemtned in the deployment guide.

2020-05-12 13:44 UTC, pavel-vasilev-georgiev-axway requested changes
I think only the Readme.md remains to be cleaned up. The rest looks ok

2020-05-28 11:52 UTC, hrtodorov approved these changes

2020-05-28 13:38 UTC, merged